version: '3.3'

services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

  db:
    image: lsioarmhf/mariadb
    volumes:
      - db_data:/config
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
    
  wordpress:
    image: arm32v7/wordpress
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: mariadb
      WORDPRESS_DB_NAME: wordpress1
    links: 
          - "db:mysql"

  nginx:
    depends_on:
       - wordpress
       - portainer
    build: ./nginx
    restart: always
    ports:
      - "80:80"
volumes:
    db_data:
    portainer_data: