version: '3.3'

services:
   db:
     image: lsioarmhf/mariadb
     volumes:
       - db_data:/config
     restart: always
     ports:
      - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: mariadb
volumes:
    db_data: